# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cffff0e27ff884a031a16ed52f0e828359b627e64991dd5d6e285baacca39b365fce1b34a3420811eecba2ed91f640e23c5d7eead51e69bd9a3f2ad3b02647db

test:
  secret_key_base: aef060bc1408ffa8b39d15ea999134af2e80456578dffa7a89c393c57d33af92b5c31a27abbb3e0c23fddc6596a5233a96c07064d190f934251753e2c8a0bf4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
